### ISSUE TITLE
Turtle Lite

### ISSUE THREAD

**Issue by cody-littley** [hiero-ledger/hiero-consensus-node#12178]
The driving factor for this feature right now is the ability to test the migration to birth rounds using the core event loop. This includes the intake queue, event creation, and consensus. At the end of the epic, we should be able to write deterministic tests that spin up one or more platforms consisting solely of the core event loops and verify:
1. A network which continuously advances in consensus
2. No ISSes
3. No error level logs

```[tasklist]
- [ ] https://github.com/hashgraph/hedera-services/issues/10982
- [ ] https://github.com/hashgraph/hedera-services/issues/10979
- [ ] https://github.com/hashgraph/hedera-services/issues/10980
- [ ] https://github.com/hashgraph/hedera-services/issues/10981
- [ ] https://github.com/hashgraph/hedera-services/issues/12171
- [ ] https://github.com/hashgraph/hedera-services/issues/12137
- [ ] #12539
- [ ] Identify which components need to be mocked/simulated
- [ ] Design strategy for validating results
- [ ] Simple test that starts TURTLE network from genesis and doesn't do anything fancy
- [ ] TURTLE test that can do shutdowns and restarts
- [ ] TURTLE test that can do a freeze upgrade workflow
- [ ] https://github.com/hashgraph/hedera-services/issues/12772
- [ ] https://github.com/hashgraph/hedera-services/issues/12799
- [ ] Non-Static `RuntimeObjectRegistry`
```

```[tasklist]
### Proxy Wiring
- [ ] https://github.com/hashgraph/hedera-services/issues/12169
- [ ] https://github.com/hashgraph/hedera-services/issues/12128
- [ ] https://github.com/hashgraph/hedera-services/issues/12131
- [ ] https://github.com/hashgraph/hedera-services/issues/12144
- [ ] https://github.com/hashgraph/hedera-services/issues/12184
- [ ] https://github.com/hashgraph/hedera-services/issues/12186
- [ ] https://github.com/hashgraph/hedera-services/issues/12148
- [ ] https://github.com/hashgraph/hedera-services/issues/12259
- [ ] https://github.com/hashgraph/hedera-services/issues/12133
- [ ] https://github.com/hashgraph/hedera-services/issues/12258
- [ ] https://github.com/hashgraph/hedera-services/issues/12257
- [ ] https://github.com/hashgraph/hedera-services/issues/12296
- [ ] https://github.com/hashgraph/hedera-services/issues/12146
- [ ] https://github.com/hashgraph/hedera-services/issues/12801
- [ ] https://github.com/hashgraph/hedera-services/issues/12971
```

```[tasklist]
### Fininsh converting things to components
- [ ] https://github.com/hashgraph/hedera-services/issues/12170
- [ ] https://github.com/hashgraph/hedera-services/issues/12174
- [ ] https://github.com/hashgraph/hedera-services/issues/12177
- [ ] https://github.com/hashgraph/hedera-services/issues/11076
- [ ] Platform Coordinator / Startup
- [ ] https://github.com/hashgraph/hedera-services/issues/12533
- [ ] https://github.com/hashgraph/hedera-services/issues/12536
- [ ] https://github.com/hashgraph/hedera-services/issues/12658
- [ ] https://github.com/hashgraph/hedera-services/issues/12657
- [ ] https://github.com/hashgraph/hedera-services/issues/12656
```
