### ISSUE TITLE
Make the State Validation Tool more usable

### ISSUE THREAD

**Issue by imalygin** [hiero-ledger/hiero-consensus-node#13092]
### Problem

This epic is about reincarnation of the state validation tool (see https://github.com/hashgraph/hedera-services/issues/5442 and https://github.com/hashgraph/hedera-services/issues/7152). The goal of this epic is to enhance the validation tool and make it available for modifications to all Hedera teams. 

### Solution

To achieve that, the following tasks should be completed

```[tasklist]
- [ ] https://github.com/hashgraph/hedera-services/issues/13093
- [ ] https://github.com/hashgraph/hedera-services/issues/5982
- [ ] Add consistency checks for linked lists
- [ ] Validate non-default ids in the state
```

**Comment by thenswan** [comment]
All sub-issues were closed
