### ISSUE TITLE
Cleanup feature flags

### ISSUE THREAD

**Issue by netopyr** [hiero-ledger/hiero-consensus-node#13567]
We have several feature flags in the code base that are no longer required. We should list all feature flags and clarify which ones can be removed.

```[tasklist]
### Obsolete Feature Flags
- [x] accounts.releaseAliasAfterDeletion
- [x] accounts.storeOnDisk
- [x] autoCreation.enabled
- [x] autorenew.grantFreeRenewals
- [x] balances.compressOnCreation
- [x] balances.exportEnabled
- [x] balances.exportTokenBalances
- [x] blockStream.compressFilesOnCreation
- [x] cryptoCreateWithAlias.enabled
- [x] dev.onlyDefaultNodeListens
- [ ] entities.limitTokenAssociations
- [ ] entities.unlimitedAutoAssociationsEnabled
- [x] hedera.allowances.isEnabled
- [x] hedera.exportAccountsOnStartup
- [x] hedera.recordStream.compressFilesOnCreation
- [x] hedera.recordStream.enabled
- [x] hedera.recordStream.logEveryTransaction
- [x] hedera.transaction.eip2930.enabled
- [x] hedera.workflows.enabled
- [x] lazyCreation.enabled
- [x] staking.isEnabled
- [x] tokens.autoCreations.isEnabled
- [x] tokens.nfts.areEnabled
- [x] tokens.nfts.useTreasuryWildcards
- [x] tokens.nfts.useVirtualMerkle
- [x] tokens.storeRelsOnDisk
- [x] utilPrng.isEnabled
```
