### ISSUE TITLE
Virtual Mega Map

### ISSUE THREAD

**Issue by artemananiev** [hiero-ledger/hiero-consensus-node#14395]
As a part of Public Merkle APIs effort, a decision was made to change the whole merkle tree to a single heterogeneous virtual map. All existing entities (singletons, queues, maps) will be stored in this map together. Entity types will very likely be reflected in virtual keys, e.g. as a string prefix. APIs to access data from this big virtual map will not change, applications will still be able to use State APIs (singletons, queues, maps) to work with strongly typed objects.

### ISS Detection Tooling Updates
- [ ] Add a draft title or issue reference here

### Eliminate FCQueue
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/15091
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/15090
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/15448
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/15412

### VirtualMap changes
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/14285
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/15411
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/14825
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/16488
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/17007
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/16785
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/14802
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/14803
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/15637
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/14502
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/16784
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/18049
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/18477
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/18478
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/19281
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/19978
- [ ] https://github.com/hashgraph/pbj/issues/389

### Migration
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/14504
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/14804

### Protobuf Serialization to Disk
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/13692
- [ ] https://github.com/hiero-ledger/hiero-consensus-node/issues/13764

### Misc Tasks
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/18248

### Prep Tasks
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/15494
- [x] https://github.com/hiero-ledger/hiero-consensus-node/issues/16098
