### ISSUE TITLE
[EPIC] HIP-1028: Enhance system contracts for TokenCreate, TokenUpdate, KeyUpdate and GetTokenInfo with metadata support

### ISSUE THREAD

**Issue by mustafauzunn** [hiero-ledger/hiero-consensus-node#14480]
### Tasks

- [x] https://github.com/hashgraph/hedera-services/issues/14481
- [x] https://github.com/hashgraph/hedera-services/issues/14482
- [x] https://github.com/hashgraph/hedera-services/issues/14317
- [x] https://github.com/hashgraph/hedera-services/issues/14483
- [x] https://github.com/hashgraph/hedera-services/issues/17809
- [x] https://github.com/hashgraph/hedera-services/issues/17811
- [x] https://github.com/hashgraph/hedera-services/issues/17816
- [x] https://github.com/hashgraph/hedera-services/issues/17817
- [x] Update HIP-1028 with versioning approach

Smart contracts task for examples and tests
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/881

**Comment by stoyanov-st** [comment]
Blocked by the System Contract versioning.

**Comment by stoyanov-st** [comment]
With the versioning plumbing merged we are now enabled to take on and refactor this HIP implementation
