### ISSUE TITLE
Labels for metrics

### ISSUE THREAD

**Issue by hendrikebbers** [hiero-ledger/hiero-consensus-node#14917]
As described in [this proposal](https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/proposals/metric-labels/README.md) we want to add the support for labels to the metrics framework. This epics groups all steps that need to be done the have the feature available

### Tasks
- [ ] Externalize API for snapshot functionality of metrics
- [ ] Add label info to snapshot
- [ ] Add label info to prometheus parsing of snapshots
- [ ] Take care of labels in CSV export

**Comment by akugal** [comment]
closed in favor of #20088
