### ISSUE TITLE
Add FeeSchedule Verification Tests

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-consensus-node#15571]
### Problem

The feeSchedule is rich in functionality and describing each HAPI transactions fee structure.
It would be good to have targeted tests focused on just this to validate expectations

### Solution

[Services BDD UtilVerbs](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java#L1741) offers an example of existing capability.
We could create a new Test Suite focused on this for base transactions for each HAPI type.

```[tasklist]
### HAPI type feeSchedule coverage suites
- [ ] Add [Crypto Service](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/crypto_service.proto) feeSchedule coverage
- [ ] Add [HSCS](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/smart_contract_service.proto) feeSchedule coverage
- [ ] Add [HFS](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/file_service.proto) feeSchedule coverage
- [ ] Add [HTS](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/token_service.proto) feeSchedule coverage
- [ ] Add [HCS](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/consensus_service.proto) feeSchedule coverage
- [ ] Add [Schedule Service](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/schedule_service.proto) feeSchedule coverage
- [ ] Add [Util Service](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/util_service.proto) feeSchedule coverage
- [ ] Add [AddressBook Service](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/address_book_service.proto) feeSchedule coverage
- [ ] Add [Freeze Service](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/freeze_service.proto) feeSchedule coverage
- [ ] Add [Network Service](https://github.com/hashgraph/hedera-services/blob/develop/hapi/hedera-protobufs/services/network_service.proto) feeSchedule coverage
```

### Alternatives

[Services BDD UtilVerbs](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java#L1741)  if not the only option, if there's a simpler approach outside of BDD this could be explored also. Goal would be to ensure at the user level the value utilized is as expected within an acceptable range.

**Comment by Nana-EC** [comment]
Issue was created to help track the matrix of transactions.
For clarity instead Services and HSCS teams used different EPIC
- Services - https://github.com/hiero-ledger/hiero-consensus-node/issues/15963
- HSCS - https://github.com/hiero-ledger/hiero-consensus-node/issues/16765

Closing as this was made redundant by #15963 as of Oct 11, 2024
