### ISSUE TITLE
HIP-904: Additional e2e tests scenarios

### ISSUE THREAD

**Issue by stoyanov-st** [hiero-ledger/hiero-consensus-node#15596]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/16240
- [ ] https://github.com/hashgraph/hedera-services/issues/16241
- [ ] https://github.com/hashgraph/hedera-services/issues/16242
- [ ] https://github.com/hashgraph/hedera-services/issues/16243
- [ ] https://github.com/hashgraph/hedera-services/issues/16244
- [ ] https://github.com/hashgraph/hedera-services/issues/16245
- [ ] https://github.com/hashgraph/hedera-services/issues/16246
- [ ] https://github.com/hashgraph/hedera-services/issues/16248
- [ ] https://github.com/hashgraph/hedera-services/issues/16249
- [ ] https://github.com/hashgraph/hedera-services/issues/16250
- [ ] https://github.com/hashgraph/hedera-services/issues/16251
- [ ] https://github.com/hashgraph/hedera-services/issues/16252
- [ ] https://github.com/hashgraph/hedera-services/issues/16253
- [ ] https://github.com/hashgraph/hedera-services/issues/16254
- [ ] https://github.com/hashgraph/hedera-services/issues/16255
- [ ] https://github.com/hashgraph/hedera-services/issues/16256
- [ ] https://github.com/hashgraph/hedera-services/issues/16257
- [ ] https://github.com/hashgraph/hedera-services/issues/16258
- [ ] https://github.com/hashgraph/hedera-services/issues/16259
- [ ] https://github.com/hashgraph/hedera-services/issues/16261
```

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/16262
- [ ] https://github.com/hashgraph/hedera-services/issues/16263
- [ ] https://github.com/hashgraph/hedera-services/issues/16264
- [ ] https://github.com/hashgraph/hedera-services/issues/16265
- [ ] https://github.com/hashgraph/hedera-services/issues/16266
- [ ] https://github.com/hashgraph/hedera-services/issues/16267
- [ ] https://github.com/hashgraph/hedera-services/issues/16268
- [ ] https://github.com/hashgraph/hedera-services/issues/16269
- [ ] https://github.com/hashgraph/hedera-services/issues/16270
- [ ] https://github.com/hashgraph/hedera-services/issues/16272
- [ ] https://github.com/hashgraph/hedera-services/issues/16273
- [ ] https://github.com/hashgraph/hedera-services/issues/16274
- [ ] https://github.com/hashgraph/hedera-services/issues/16275
- [ ] https://github.com/hashgraph/hedera-services/issues/16276
- [ ] https://github.com/hashgraph/hedera-services/issues/16277
- [ ] https://github.com/hashgraph/hedera-services/issues/16278
- [ ] https://github.com/hashgraph/hedera-services/issues/16279
- [ ] https://github.com/hashgraph/hedera-services/issues/16280
- [ ] https://github.com/hashgraph/hedera-services/issues/16281
- [ ] https://github.com/hashgraph/hedera-services/issues/16282
- [ ] https://github.com/hashgraph/hedera-services/issues/16283
- [ ] https://github.com/hashgraph/hedera-services/issues/16284
- [ ] https://github.com/hashgraph/hedera-services/issues/16285
- [ ] https://github.com/hashgraph/hedera-services/issues/16286
- [ ] https://github.com/hashgraph/hedera-services/issues/16287
- [ ] https://github.com/hashgraph/hedera-services/issues/16288
- [ ] https://github.com/hashgraph/hedera-services/issues/16289
- [ ] https://github.com/hashgraph/hedera-services/issues/16290
- [ ] https://github.com/hashgraph/hedera-services/issues/16291
- [ ] https://github.com/hashgraph/hedera-services/issues/16292
- [ ] https://github.com/hashgraph/hedera-services/issues/16293
- [ ] https://github.com/hashgraph/hedera-services/issues/16294
- [ ] https://github.com/hashgraph/hedera-services/issues/16295
- [ ] https://github.com/hashgraph/hedera-services/issues/16296
- [ ] https://github.com/hashgraph/hedera-services/issues/16345
- [ ] https://github.com/hashgraph/hedera-services/issues/16346
- [ ] https://github.com/hashgraph/hedera-services/issues/16347
- [ ] https://github.com/hashgraph/hedera-services/issues/16349
```

**Comment by stoyanov-st** [comment]
# Test Cases for Airdrop to Contract

## Receiver IS Associated

| Number                     | Test Description                                                             | Test Details | Expected Result |
|----------------------------|-------------------------------------------------------------------------------|--------------|-----------------|
| AIRDROP_TO_CONTRACT_01      | EOA Airdrops a token to a Contract who is associated to the token              |              | The token should be transferred to the contract without creating a pending airdrop. No association fee or rent should be paid. The contract’s `automatic_association` field should be incremented. |
| AIRDROP_TO_CONTRACT_02      | EOA airdrops multiple tokens to a contract that is associated to all of them    |              | The tokens should be transferred to the contract account. No association fees should be paid. |
| AIRDROP_TO_CONTRACT_03      | Airdrop multiple tokens to a contract that is associated to SOME of them when the contract has free auto association slots. <br> Case 1: associated only to FT <br> Case 2: associated only to NFT |              | All tokens should be transferred to the contract account. The contract should get associated to the not associated tokens. The sender should pay the association fees for the new associations. |
| AIRDROP_TO_CONTRACT_04      | Given a contract with NO free association slots and a balance of 1 FT A. When the sender airdrops 1 FT A + 1 FT B, then the contract should have 1 FT A transferred to their balance and 1 pending airdrop for 1 FT B. |              | The contract should receive the tokens it is associated to and a pending airdrop for the tokens it is not associated to. The sender should pre-pay for the association of the not associated tokens. |
| AIRDROP_TO_CONTRACT_05      | Sender airdrops a token with a custom fee to be paid by the receiver to the fee collector account for the token fee when the fee collector account is a contract. |              | The token should be transferred to the receiver (the contract) and no custom fee should be paid. |
| AIRDROP_TO_CONTRACT_06      | Sender airdrops a token with a custom fee to be paid by the receiver to the fee collector account of another token fee when all fee collector accounts are exempt. The fee collector account (receiver) is a contract. |              | The token should be transferred to the receiver and no custom fee should be paid. |
| AIRDROP_TO_CONTRACT_07      | Sender airdrops a token with a custom fee to be paid by the receiver to the token treasury account, when this account is a contract. |              | The token should be transferred to the receiver and no custom fee should be paid. |

## Receiver NOT Associated

| Number                     | Test Description                                                             | Test Details | Expected Result |
|----------------------------|-------------------------------------------------------------------------------|--------------|-----------------|
| AIRDROP_TO_CONTRACT_09      | EOA account airdrops a single token to a contract with free association slots <br> for FT and NFT |              | The contract gets associated to the token and receives them. The sender pays the association fee. |
| AIRDROP_TO_CONTRACT_10      | EOA account airdrops a single token to a contract, deployed via CREATE2 on a hollow account address alias (the contract won’t have any free auto association slots) <br> for FT and NFT |              | `TokenAirdropTransaction` should fail with: NOT_SUPPORTED. |
| AIRDROP_TO_CONTRACT_11      | EOA account airdrops a single token to a contract with `maxAutoAssociations = 0` <br> for FT and NFT |              | `TokenAirdropTransaction` should fail with: NOT_SUPPORTED. |
| AIRDROP_TO_CONTRACT_13      | EOA account airdrops a single token to a contract with NO free association slots (`maxAutoAssociations = 1` and 1 auto association is already used) <br> for FT and NFT |              | `TokenAirdropTransaction` should fail with: NOT_SUPPORTED. |
| AIRDROP_TO_CONTRACT_14      | EOA account airdrops multiple tokens to a contract with free auto association slots |              | All tokens should be transferred to the contract. The sender should pay for the association fees. |
| AIRDROP_TO_CONTRACT_15      | EOA account airdrops multiple tokens to a contract with NO free auto association slots |              | `TokenAirdropTransaction` should fail with: NOT_SUPPORTED. |
| AIRDROP_TO_CONTRACT_20      | Multiple EOA accounts airdrop tokens to multiple contracts (up to 10): <br> - Multiple senders to a single contract <br> - Multiple senders to multiple contracts <br> THE CONTRACTS NEED TO HAVE FREE AUTO ASSOCIATION SLOTS! |              | The transaction payer should pay for each association. If 2 senders send the same token to 1 receiver, only 1 association fee should be paid. |
| AIRDROP_TO_CONTRACT_21      | EOA airdrops up to 10 tokens: <br> - to the same contract <br> - to multiple contracts <br> THE CONTRACTS NEED TO HAVE

## Receiver NOT Associated

| Number                     | Test Description                                                             | Test Details | Expected Result |
|----------------------------|-------------------------------------------------------------------------------|--------------|-----------------|
| AIRDROP_TO_CONTRACT_28      | Airdrop a token to a contract that is not associated to the token and HAS free autoAssociation slots. |                                                                                                                   | TokenAirdropTransaction is successful and the tokens should be successfully associated and transferred to the contract. The sender should pay association fee + trx fee + any custom fees (if any). receiver’s automatic_association field should be incremented. |

## Negative cases
## Receiver IS Associated

| Number                     | Test Description                                                             | Test Details | Expected Result |
|----------------------------|-------------------------------------------------------------------------------|--------------|-----------------|
| AIRDROP_TO_CONTRACT_30      | Airdrop a token to a contract that is associated to the token and is frozen for it |                                                                                                                   | TokenAirdropTransaction should fail with error message: `ACCOUNT_FROZEN_FOR_TOKEN`                                                                                                      |
| AIRDROP_TO_CONTRACT_31      | Given a contract has a pending airdrop when the sender signs a cryptoTransfer to the contract for the airdropped token then the airdrop should remain in pending and the cryptoTransfer should fail with error message TOKEN_NOT_ASSOCIATED_TO_ACCOUNT | Alice is the treasury account for FT A. 1. Alice sings a tokenAirdropTransaction for 1 FT A to Contract A. 2. Alice signs a cryptoTransfer for 1 FT A to Contract A. | 1. Successful tokenAirdropTransaction. Alice should pay 1 association fee and airdrop transaction fee. Contract A = 1 pending airdrop for 1 FT A. 2. CryptoTransfer transaction should fail with error message `TOKEN_NOT_ASSOCIATED_TO_ACCOUNT`. Contract A = 1 pending airdrop for 1 FT A. |

## Receiver NOT Associated

| Number                     | Test Description                                                             | Test Details | Expected Result |
|----------------------------|-------------------------------------------------------------------------------|--------------|-----------------|
| AIRDROP_TO_CONTRACT_32      | CryptoTransfer to a contract not associated to the token and with no auto association slots left should result in a failing cryptoTransfer and no airdrops should be created. |                                                                                                                   | The cryptoTransfer should fail with an error message: `TOKEN_NOT_ASSOCIATED_TO_ACCOUNT`                                                                                                      |
| AIRDROP_TO_CONTRACT_33      | CryptoTransfer to a contract with no Admin key |                                                                                                                   |                                                                                                                                                                   |
| AIRDROP_TO_CONTRACT_34      | 1. TokenAirdropTransaction to a hollow account with maxAutoAssociations ≠ -1 2. CREATE2 a contract on an address with a hollow account with maxAutoAssociations ≠ -1 |                                                                                                                   | 1. Pending airdrop. 2. Contract is deployed.                                                                                                                                                                   |

**Comment by bubo** [comment]
I'll take the task.

**Comment by Nana-EC** [comment]
There's a lot of good coverage here.
Let's break the remaining into a P1 and P2 list.
Preferably let's get it all done in 0.59.0 B but if delays continue P1 should be the main goal

**Comment by Ferparishuertas** [comment]
As we have a good coverage, We withdraw all the P2 tesst
