### ISSUE TITLE
Drop MerkleMap

### ISSUE THREAD

**Issue by artemananiev** [hiero-ledger/hiero-consensus-node#15918]
`MerkleMap` is a legacy in-memory data structure, which is no longer used in Hedera services. After other apps (PTT, MTT, tests) are updated to use virtual maps instead, this class can be removed.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/15915
- [ ] https://github.com/hashgraph/hedera-services/issues/15916
- [ ] https://github.com/hashgraph/hedera-services/issues/15917
- [ ] Remove MerkleMap class
```
