### ISSUE TITLE
[EPIC] CITR Phase 2

### ISSUE THREAD

**Issue by rbarker-dev** [hiero-ledger/hiero-consensus-node#16382]
**Background**:

See the [CITR Phase 2 Design](https://lucid.app/lucidchart/efc6708c-8096-4056-8ec0-52ccbbd438b7/edit?page=CUbJM5xeWVcw#)

Phase 2 introduces the single day performance testing component of CITR 

**Deliverables**:

- Add new CI pipelines to run the Phase-1 Build ID in one of the single-day test nodes
- Publication of OCI compliant container images for the performance suites that Tom & Oleg have been running
- User controlled workflow for build promotion/tagging to enable Single Day Longevity Tests (phase 3 product)

There is additional work in Phase 2 that has been in work from the release engineering team. However the devops-ci component of this work has not yet began.

### Tasks
- [x] #16383
- [x] #16384
- [x] #16385
- [x] #16409
- [x] #16410
- [x] Add workflow where user can specify a build ID to call semantic release (in PR #17332)
- [x] workflow where user can call to do a minor version roll automatically (in PR #17332)
- [x] #17244
- [x] Additional verification for validate testing has passed successfully (additional tag on the commit)
