### ISSUE TITLE
Recuperate Block Streams Performance Loss

### ISSUE THREAD

**Issue by mhess-swl** [hiero-ledger/hiero-consensus-node#16970]
This epic tracks the ongoing investigation into loss of performance from turning on the block streams preview. 

# Context

Release v0.56 enables the first block streams preview in production environments. In preparation for this release, @OlegMazurov discovered from our nightly performance tests that there is a ~15% drop in average TPS at high loads (see the original issue [here](https://github.com/hashgraph/hedera-services/issues/16365)). Subsequent failing performance tests and other manual tests have since confirmed this.

# Current Status

Initial analysis indicated that the majority of the regression resides in `BlockStreamManagerImpl#endRound()`, specifically waiting for a call to `future.join()`. Our latest attempt offloaded the manager's block writing to a background thread; while doing so did regain some performance speed, it did not entirely fix the problem. The following issues still remain: 
* `FileBlockItemWriter.openBlock()` creates 3 large buffers on every invocation. Initializing these buffers costs 5% of transaction handling time
* Another 5% is (still) spent waiting for `hashFuture.join()` in `endRound()`. It turns out that the write background thread often submits to an idle pool, thus invoking many expensive thread wakes
* If we succeed in finding a solution to write block items asynchronously, we also need to provide a back-pressure mechanism to keep the consensus node from crashing

Our next attempt will entail refactoring all `BlockStreamManagerImpl` operations to submit to an ordered background thread. 

```[tasklist]
### Task List
- [x] Replicate the performance issue
- [x] Investigate cause of the regression (see also #16365)
- [x] Attempt to regain performance by making block file writes asynchronous – PR #16910
- [ ] https://github.com/hashgraph/hedera-services/issues/17012
- [ ] https://github.com/hashgraph/hedera-services/issues/17093
- [ ] https://github.com/hashgraph/hedera-services/issues/17098
- [ ] https://github.com/hashgraph/hedera-services/issues/17231
- [ ] Verify recuperated performance with more load testing
```

**Comment by mhess-swl** [comment]
No longer useful to keep this around, no active work on it for some time.
