### ISSUE TITLE
HIP-631: Update account state definition

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hiero-ledger/hiero-consensus-node#4833]
### Problem

This epic contains tasks needed to implement Phase 1 of HIP-631.

### Solution:
  - [ ] https://github.com/hashgraph/hedera-services/issues/4834
  - [ ] https://github.com/hashgraph/hedera-services/issues/4835
  - [x] https://github.com/hashgraph/hedera-services/issues/4836
  - [ ] https://github.com/hashgraph/hedera-services/issues/4837
