### ISSUE TITLE
CI Workflow & Docker Image Enhancements

### ISSUE THREAD

**Issue by nathanklick** [hiero-ledger/hiero-consensus-node#9444]
## Description

This epic level issue tracks all outstanding CI workflow enhancements, changes, and bug fixes. 

### Issues
- [ ] https://github.com/hashgraph/hedera-services/issues/11022
- [ ] https://github.com/hashgraph/hedera-services/issues/9445
- [ ] https://github.com/hashgraph/hedera-services/issues/10654
- [ ] https://github.com/hashgraph/hedera-services/issues/10656
- [ ] https://github.com/hashgraph/hedera-services/issues/10413
- [ ] https://github.com/hashgraph/hedera-services/issues/10195
- [ ] https://github.com/hashgraph/hedera-services/issues/10459
- [ ] https://github.com/hashgraph/hedera-services/issues/10192
- [ ] https://github.com/hashgraph/hedera-services/issues/10454
- [ ] https://github.com/hashgraph/hedera-services/issues/10269
- [ ] https://github.com/hashgraph/hedera-services/issues/10028
- [ ] https://github.com/hashgraph/hedera-services/issues/10354
- [ ] https://github.com/hashgraph/hedera-services/issues/10311
- [ ] https://github.com/hashgraph/hedera-services/issues/10339
- [ ] https://github.com/hashgraph/hedera-services/issues/9691
- [ ] https://github.com/hashgraph/hedera-services/issues/9692
- [ ] https://github.com/hashgraph/hedera-services/issues/9693
- [ ] https://github.com/hashgraph/hedera-services/issues/9711
- [ ] https://github.com/hashgraph/hedera-services/issues/9758
- [ ] https://github.com/hashgraph/hedera-services/issues/9773
- [ ] https://github.com/hashgraph/hedera-services/issues/10031
- [ ] https://github.com/hashgraph/hedera-services/issues/10069
- [ ] https://github.com/hashgraph/hedera-services/issues/10180
- [ ] https://github.com/hashgraph/hedera-services/issues/10191
- [ ] https://github.com/hashgraph/hedera-services/issues/10193
- [ ] https://github.com/hashgraph/hedera-services/issues/10194
- [ ] https://github.com/hashgraph/hedera-services/issues/10202
- [ ] https://github.com/hashgraph/hedera-services/issues/10229
- [ ] https://github.com/hashgraph/hedera-services/issues/10241
- [ ] https://github.com/hashgraph/hedera-services/issues/11117
- [ ] https://github.com/hashgraph/hedera-services/issues/11118
- [ ] https://github.com/hashgraph/hedera-services/issues/11119
- [ ] https://github.com/hashgraph/hedera-services/issues/11266
- [ ] https://github.com/hashgraph/hedera-services/issues/12087
- [ ] https://github.com/hashgraph/hedera-services/issues/11777
- [ ] https://github.com/hashgraph/hedera-services/issues/11776
- [ ] https://github.com/hashgraph/hedera-services/issues/11781
- [ ] https://github.com/hashgraph/hedera-services/issues/11782
- [ ] https://github.com/hashgraph/hedera-services/issues/12397
- [ ] https://github.com/hashgraph/hedera-services/issues/12403
- [ ] https://github.com/hashgraph/hedera-services/issues/13156
- [ ] https://github.com/hashgraph/hedera-services/issues/13420

**Comment by andrewb1269hg** [comment]
Removing 
- [ ] https://github.com/hashgraph/hedera-services/issues/11590
from the above list so we can close out the epic.
